### ISSUE TITLE
Make offline install option more easily accessible

### ISSUE THREAD

**Issue by BC46** [oliverpechey/Freelancer-hd-edition-install-script#58]
Here's the idea I had:
When the installer opens, ask the user whether they want to do an online or offline install. If they choose the online install, simply continue the installation like usual. 

When they choose the offline option though, they'll see a screen where they can download the zip to a location somewhere on their PC. Once that's done, they can exit the installer, or install the mod from that zip.

On the offline install page, there should also be an option to install from a downloaded zip right away, without having to download the zip again.

**Comment by ollieraikkonen** [comment]
Agreed, we need this. Will take a look.

**Comment by BC46** [comment]
We might not actually need it at this time since the v0.6 zip will most likely be below 2.1 GB. Moving this to the backlog.

**Comment by BC46** [comment]
I don't think we need this anymore considering we can use up to 6 GB of mod content for all-in-one installs. Feel free to reopen this issue if the need arises again.
