### ISSUE TITLE
Download almost always fails at 2047 MB on Linux (Wine)

### ISSUE THREAD

**Issue by BC46** [oliverpechey/Freelancer-hd-edition-install-script#76]
Linux users who are using the installer through Wine usually encounter an issue where the download stops at 2047 MB. This mark is 1 MB away from 2 GB, which I don't think is a coincidence.

The weird part is that for Wine users the download does seem to succeed with the GitHub mirror. Back when this mirror used to be the main one, people with slower internet connections often experienced issues with it. If we can prove that these issues don't occur for Wine users, we should consider making GitHub the primary mirror for them.

**Comment by silelmot** [comment]
can confirm that the download stopps at 2047 all the time.
tried an older install (v0.4.1-3) which worked,
deleted for testing purposes the mirrors of the newest install file to only use the github one, and also worked.

**Comment by BC46** [comment]
If everything goes well, version 0.6 will ship with an all-in-one offline installer. So that should resolve this issue.

**Comment by ollieraikkonen** [comment]
Hi @tgmatt ,

Give this a go: https://github.com/BC46/freelancer-hd-edition/wiki/How-to-install-Freelancer:-HD-Edition-in-offline-mode

**Comment by BC46** [comment]
All-in-one installers are now available for version 0.5 and 0.4.1.

**Comment by oliverpechey** [comment]
Hi mate,

Give this a go:
https://github.com/BC46/freelancer-hd-edition/wiki/How-to-install-Freelancer:-HD-Edition-in-offline-mode
